config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/mixins/room_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2 " style="background-image: url({{room.first_photo}});"></div>
        <div class="flex justify-between mb-2 truncate">
            <div class="w-4/5 overflow-hidden flex">
                {% if room.host.superhost %}
                    <span class="mr-2 uppercase font-medium text-xs border border-black text-black rounded py-px px-1">Superhost</span>
                {% endif %}
                <span class="text-sm text-gray-600 block truncate">{{room.city}}, {{room.country.name}}</span>
            </div>
            <span class="text-sm flex items-center">
                <i class="fas fa-star text-red-500 text-xs mr-1"></i> {{room.total_rating}}
            </span>
        </div>
        <span class="text-black w-11/12 block truncate">{{room.name}}</span>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
    <div class="h-20 w-20 rounded-full bg-cover" style="background-image: url({{user.avatar.url}});">
{% else %}
    <div class="h-20 w-20 bg-gray-700 rounded-full text-white flex justify-center items-center overflow-hidden">
        <span class="text-3xl">{{user.first_name|first}}</span>
    {% endif %}
</div> 