config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block page_title %}{% endblock page_title %}| Nbnb</title>
  </head>
  <body class="text-gray-800 mt-24 font-light">
    {% include "partials/messages.html" %}
    <header class="container max-w-full inset-0 flex items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white">
      <div class="flex items-center w-1/3">
        <a href="{% url "core:home" %}" class="mr-6">
            <img class="w-8" src="{% static 'img/logo.png' %}" />
        </a>
        {% block search-bar %}
        <form method="get" action="{% url 'rooms:search' %}" class="w-9/12">
          <input class="search-box border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-sm w-64 shadow-md hover:shadow-lg focus:outline-none" name="city" placeholder="Search By City" />
        </form>
        {% endblock search-bar %}
      </div>
      {% include "partials/nav.html" %}
    </header>

    {% block content %}{% endblock %}
    {% include "partials/footer.html" %}
  </body>
</html>